# 共通の設定を定義する
spring:
  profiles:
    include: common
    # デフォルトを明示的に指定する
    # ローカル環境以外は環境変数でプロファイルを切り替える
    default: local
    active: local
  main:
    # DataValueProcessorのBean上書きのため暫定対応
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      autoCommit: false
      connectionTimeout: 30000
      idleTimeout: 5000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      minimumIdle: 10
      maximumPoolSize: 30
  mvc.hiddenmethod.filter.enabled: true
  batch:
    job:
      # 自動的にバッチジョブが起動しないようにする
      enabled: false
  mail:
    default-encoding: ISO-2022-JP
    protocol: smtp

doma:
  dialect: mysql
  # 小文字のスネークケースに変換する（firstName → first_name）
  naming: SNAKE_LOWER_CASE
  # バルクインサート・アップデートのサイズ
  batch-size: 1000

logging:
  pattern:
    # MDCで設定した値を出力する
    level: "[%X{FUNCTION_NAME}:%X{X-Track-Id}:%X{LOGIN_USER_ID}] %5p"
